#!/bin/bash

echo "DashPlus Build Script."
echo "Setting build directory to:" $(pwd)

export dashplus_path=$(pwd)

cd build

if [ "$1" = "--clean" ]
then
    echo "Executing clean build."
    rm -rf *
fi

if [ "$2" = "--clean" ]
then
    echo "Executing clean build."
    rm -rf *
fi

cmake ..
make

if [ "$1" = "--run" ]
then
    echo "Running executable."
    ./dashplus
fi

if [ "$2" = "--run" ]
then
    echo "Running executable."
    ./dashplus
fi

echo ">> Build complete."